#include <stdio.h>
#include <stdlib.h>

#include "hit_detec.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/startscreen.h"
#include "images/background.h"
#include "images/cheese.h"
#include "images/lossscreen.h"
#include "images/winscreen.h"
#include "images/rat_image_noback.h"
#include "images/trap_im.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  LOAD,
  PLAY,
  WIN,
  LOSE,
  IDLE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  //Additional variables for the manipulation of states, etc.
  rat newrat;
  rat *rp = &newrat;
  createRat(rp);
  rat prevrat = newrat;

  int size = sizevar;

  struct cheese cheeses[sizevar];
  struct trap traps[sizevar];

  int check_trap = 0;
  int check_end = 0;  
  int check_cheese = 0;
  int score = 0;

  struct endgoal endg;
  struct endgoal* endgp = &endg;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //

    // resets the state if start is pressed at any point. the additional reloads with all the other states will be generated in the
    // load phase, so inherently everything is reset following this.
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0) {
      check_trap = 0;
      check_end = 0;
      check_cheese = 0;
      score = 0;
      state = START;
    }

    if (check_end == 1) {
      state = WIN;
      check_end = 0;
    }
    
    if (check_trap == 1) {
      state = LOSE;
      check_trap = 0;
    }
    
    waitForVBlank();

    switch (state) {
      case START:
        // draws start screen and waits until check to start the game
        drawFullScreenImageDMA(startscreen);
        char buffer[51]; 

        sprintf(buffer, "AW RATS!");
        drawString(23, 181, buffer, BLACK);

        sprintf(buffer, "[Start]: Play!");
        drawString(43, 145, buffer, BLACK);

        state = IDLE;
        break;
      case LOAD:
        // loading all the initial images, the bakground, the initial traps and cheeses
        size = sizevar;
        createArrs(cheeses, traps, sizevar);

        createRat(rp);
        createEnd(endgp);
        
        drawFullScreenImageDMA(background);
        drawCheese(cheeses, size);
        drawTrap(traps, sizevar);
        score = 0;

        state = PLAY;

        break;
      case PLAY:
        // updates player movement, undraws pixels of player's prev location, draws the new ones, draws other necessary items
        // checks if player hit a trap, if so, state should be loss screen next time
        // if they hit a cheese, the cheese is removed from the array of drawn cheeses and the score is incremented
        // also checks for if player made it to the end goal
        performCalcs(currentButtons, previousButtons, rp);
        undrawImageDMA(prevrat.x, prevrat.y, prevrat.wide, prevrat.len, background);
        drawImageDMA(newrat.x, newrat.y, newrat.wide, newrat.len, rat_image_noback);
        drawCheese(cheeses, size);
        drawTrap(traps, sizevar);
        
        check_trap = hit_trap(rp, traps, sizevar);
        check_end = hit_goal(rp, endg);
        check_cheese = hit_cheese(rp, cheeses, &size, &score);
  
        sprintf(buffer, "Score: %d", score);   
        drawRectDMA(150, 11, 71, 10, BLACK);  
        drawString(151, 16, buffer, WHITE);  

        if (check_cheese > 0) {
          check_cheese = 0;
        }

        break;
      case WIN:
        // Cover the previous screen, put up win screen and go to idle phase -- no point redrawing all this stuff every frame
        fillScreenDMA(BLACK);
        drawImageDMA(2, 1, WINSCREEN_WIDTH, WINSCREEN_HEIGHT, winscreen);
        
        sprintf(buffer, "    YOU WON!");
        drawString(40, 130, buffer, WHITE);

        sprintf(buffer, " Final Score: %d", score);
        drawString(60, 127, buffer, WHITE);
        
        sprintf(buffer, " [Select]: Title");
        drawString(100, 130, buffer, WHITE);

        sprintf(buffer, " [Start]: Again!");
        drawString(120, 130, buffer, WHITE);

        state = IDLE;
        break;
      case LOSE:
        // Cover the previous screen, put up loss screen and go to idle phase -- no point redrawing all this stuff every frame
        drawFullScreenImageDMA(lossscreen); 

        sprintf(buffer, "YOU LOST");
        drawString(110, 5, buffer, WHITE);

        sprintf(buffer, "Collected Cheese: %d/%d", score / 100, sizevar);
        drawString(120, 5, buffer, WHITE);

        sprintf(buffer, "[Start]: Again!");
        drawString(140, 5, buffer, WHITE);

        sprintf(buffer, "[Select]: Title");
        drawString(150, 5, buffer, WHITE);

        state = IDLE;
        break;
      case IDLE:
        // checks for start button during the idle phase to see if player wants to play again
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          check_trap = 0;
          check_end = 0;
          check_cheese = 0;
          score = 0;
          state = LOAD;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
    prevrat = newrat;
  }
  return 0;
}
